---
language: python
sudo: false
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=py27-distlib_0_2_4
  - TOXENV=py36-distlib_0_2_4
  - TOXENV=cover
install:
  - pip install tox
script:
  - tox
